# Wrangler configuration for Cloudflare Pages
name = "gestion-asador-callejero"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "asador-callejero-db"
database_id = "to-be-set-after-creation"

# Pages configuration
pages_build_output_dir = "."

[env.production]
# Production environment settings
vars = { ENVIRONMENT = "production" }

[env.preview]
# Preview/staging environment settings
vars = { ENVIRONMENT = "preview" }
